name: human_duration_parser
description: Parse human readable duration into Dart's duration
version: 3.0.0
homepage: https://github.com/l7ssha/duration_parser

environment:
  sdk: '>2.18.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
